// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	web "golang-api/modules/cart/models/web"

	wrapper "golang-api/utils/wrapper"
)

// Usecases is an autogenerated mock type for the Usecases type
type Usecases struct {
	mock.Mock
}

// CreateCart provides a mock function with given fields: ctx, payload
func (_m *Usecases) CreateCart(ctx context.Context, payload *web.RequestCreateCart) wrapper.Result {
	ret := _m.Called(ctx, payload)

	var r0 wrapper.Result
	if rf, ok := ret.Get(0).(func(context.Context, *web.RequestCreateCart) wrapper.Result); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(wrapper.Result)
	}

	return r0
}

// GetAllCart provides a mock function with given fields: ctx, payload
func (_m *Usecases) GetAllCart(ctx context.Context, payload *web.RequestListCart) wrapper.Result {
	ret := _m.Called(ctx, payload)

	var r0 wrapper.Result
	if rf, ok := ret.Get(0).(func(context.Context, *web.RequestListCart) wrapper.Result); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(wrapper.Result)
	}

	return r0
}

// NewUsecases creates a new instance of Usecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *Usecases {
	mock := &Usecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
