// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeBookServiceServer is an autogenerated mock type for the UnsafeBookServiceServer type
type UnsafeBookServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedBookServiceServer provides a mock function with given fields:
func (_m *UnsafeBookServiceServer) mustEmbedUnimplementedBookServiceServer() {
	_m.Called()
}

// NewUnsafeBookServiceServer creates a new instance of UnsafeBookServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeBookServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeBookServiceServer {
	mock := &UnsafeBookServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
