// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/books_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author string  `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Year   string  `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	Price  float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *BookData) Reset() {
	*x = BookData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_books_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookData) ProtoMessage() {}

func (x *BookData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookData.ProtoReflect.Descriptor instead.
func (*BookData) Descriptor() ([]byte, []int) {
	return file_proto_books_data_proto_rawDescGZIP(), []int{0}
}

func (x *BookData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookData) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookData) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *BookData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BookDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author string  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Year   string  `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	Price  float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *BookDataRequest) Reset() {
	*x = BookDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_books_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDataRequest) ProtoMessage() {}

func (x *BookDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDataRequest.ProtoReflect.Descriptor instead.
func (*BookDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_books_data_proto_rawDescGZIP(), []int{1}
}

func (x *BookDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookDataRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookDataRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *BookDataRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BookDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data    *BookData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BookDataResponse) Reset() {
	*x = BookDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_books_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDataResponse) ProtoMessage() {}

func (x *BookDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDataResponse.ProtoReflect.Descriptor instead.
func (*BookDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_books_data_proto_rawDescGZIP(), []int{2}
}

func (x *BookDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BookDataResponse) GetData() *BookData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_books_data_proto protoreflect.FileDescriptor

var file_proto_books_data_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x5f, 0x61, 0x70, 0x69, 0x22, 0x70, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x67, 0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22,
	0x56, 0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x28, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_books_data_proto_rawDescOnce sync.Once
	file_proto_books_data_proto_rawDescData = file_proto_books_data_proto_rawDesc
)

func file_proto_books_data_proto_rawDescGZIP() []byte {
	file_proto_books_data_proto_rawDescOnce.Do(func() {
		file_proto_books_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_books_data_proto_rawDescData)
	})
	return file_proto_books_data_proto_rawDescData
}

var file_proto_books_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_books_data_proto_goTypes = []interface{}{
	(*BookData)(nil),         // 0: golang_api.BookData
	(*BookDataRequest)(nil),  // 1: golang_api.BookDataRequest
	(*BookDataResponse)(nil), // 2: golang_api.BookDataResponse
}
var file_proto_books_data_proto_depIdxs = []int32{
	0, // 0: golang_api.BookDataResponse.data:type_name -> golang_api.BookData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_books_data_proto_init() }
func file_proto_books_data_proto_init() {
	if File_proto_books_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_books_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_books_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_books_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_books_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_books_data_proto_goTypes,
		DependencyIndexes: file_proto_books_data_proto_depIdxs,
		MessageInfos:      file_proto_books_data_proto_msgTypes,
	}.Build()
	File_proto_books_data_proto = out.File
	file_proto_books_data_proto_rawDesc = nil
	file_proto_books_data_proto_goTypes = nil
	file_proto_books_data_proto_depIdxs = nil
}
