// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// GrpcServerInterface is an autogenerated mock type for the GrpcServerInterface type
type GrpcServerInterface struct {
	mock.Mock
}

// GetServer provides a mock function with given fields:
func (_m *GrpcServerInterface) GetServer() *grpc.Server {
	ret := _m.Called()

	var r0 *grpc.Server
	if rf, ok := ret.Get(0).(func() *grpc.Server); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.Server)
		}
	}

	return r0
}

// NewGrpcServerInterface creates a new instance of GrpcServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrpcServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrpcServerInterface {
	mock := &GrpcServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
