// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	web "golang-api/modules/users/models/web"

	wrapper "golang-api/utils/wrapper"
)

// Usecases is an autogenerated mock type for the Usecases type
type Usecases struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, payload
func (_m *Usecases) CreateUser(ctx context.Context, payload *web.RequestCreateUser) wrapper.Result {
	ret := _m.Called(ctx, payload)

	var r0 wrapper.Result
	if rf, ok := ret.Get(0).(func(context.Context, *web.RequestCreateUser) wrapper.Result); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(wrapper.Result)
	}

	return r0
}

// LoginUser provides a mock function with given fields: ctx, payload
func (_m *Usecases) LoginUser(ctx context.Context, payload *web.RequestLogin) wrapper.Result {
	ret := _m.Called(ctx, payload)

	var r0 wrapper.Result
	if rf, ok := ret.Get(0).(func(context.Context, *web.RequestLogin) wrapper.Result); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(wrapper.Result)
	}

	return r0
}

// NewUsecases creates a new instance of Usecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *Usecases {
	mock := &Usecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
